"""init

Revision ID: 9d1c4bee7d6f
Revises: 
Create Date: 2021-05-13 08:24:27.915839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d1c4bee7d6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calculations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('action', sa.Integer(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file')
    )
    op.create_index(op.f('ix_calculations_status'), 'calculations', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calculations_status'), table_name='calculations')
    op.drop_table('calculations')
    # ### end Alembic commands ###
